### PR TITLE
Adjust the regex used in Base64StringIO for docx

### LINKED ISSUE #45: Failure when uploading docx file
When uploading a docx file which Content-Type is `application/vnd.openxmlformats-officedocument.wordprocessingml.document` (yes I know this looks retarded) carrierwave-base64 will fail to extract the proper media type because the `regex` in `get_file_format` method in `Base64StringIO` class doesn't account for dots and hyphens.

Fixing that is trivial (I will open a PR shortly) but another issue arises - namely `original_filename` method will blatantly paste the bit after `application/` as the file extension which, in turn, will definitely fail the check in `extension_whitelist` in the uploader if you try listing `docx` there.

Could we possibly try looking up the file extension by some mime-type magic?

### PR DESCRIPTION
**Pull request by Quintasan**
Closes #45. While this does work it is merely a workaround since the
proper file extension (ie. docx) is not derived from the MIME type.

### CODE REVIEW

**Comment by Quintasan** [comment]
Should d302155 be too invasive for your style preferences (BlockLength metric is bollocks in my opinion and it only makes the spec fail) I can revert it.

2d32331 just removes Ruby 2.0.0 because we're pulling Rack 2.0 which requires Ruby >= 2.2.2 (how does 2.1.9 pass is beyond me though and I'm not sure I want to dig into Travis right now)

**Comment by lebedev-yury** [comment]
@Quintasan I don't agree with disabling so many cops at once, just to make your specs pass. Removing 2.0 ruby support from travis is though.

**Comment by Quintasan** [comment]
@lebedev-yury Is it okay to disable the BlockSize cop then?

**Comment by lebedev-yury** [comment]
@Quintasan: let's disable the `BlockLength` cop only for the `spec` folder?

Just add this to `rubocop.yml`:

```
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
```

**Comment by Quintasan** [comment]
@lebedev-yury

**Comment by lebedev-yury** [comment]
@Quintasan thank you! I will release a new minor version, and add you to the changelog.

Btw, regarding green travis build: it was green because it installed the version of rack that was lower than 2.0. So technically it was broken before also for rack 2.0

**Comment by lebedev-yury** [comment]
@Quintasan and thanks for the contribution

**Pull request merged**
