### PR TITLE
Raise deprecation warning on adapter instead of Base64StringIO.

### PR DESCRIPTION
**Pull request by frodsan**
Currently, I'm getting the warning even when I set up file_name as a proc:

```
mount_base64_uploader :avatar, UserAvatarUploader, file_name: ->(_) { SecureRandom.hex(8) }
```

In order to fix the warning at the moment, you have to do this:

```
mount_base64_uploader :avatar, UserAvatarUploader, file_name: ->(_) { -> { SecureRandom.hex(8) } }
```

I don't think the latter is intended to do

### CODE REVIEW

**Comment by frodsan** [comment]
Previous version was only testing deprecation on the Base64 class which is not part of the public API that's why this case wasn't reported by the test suite.

**Comment by frodsan** [comment]
All rubocop warnings have been fixed.

**Comment by lebedev-yury** [comment]
Included in 2.5.3

**Comment by frodsan** [comment]
Thanks!

**Comment by lebedev-yury** [comment]
@frodsan Thank you!

**Pull request merged**
