### PR TITLE
Raise error whitespace base64 string

### PR DESCRIPTION
**Pull request by sjdrabbani**
Raising an error if the Base64 string contains any whitespace.

### CODE REVIEW

**Comment by lebedev-yury** [comment]
@sjdrabbani thank you for your contribution, but I don't see a reason why we should reinvent the wheel here.

`Base64` module has a method [`strict_decode64`](https://ruby-doc.org/stdlib-2.1.3/libdoc/base64/rdoc/Base64.html#method-i-strict_decode64), which raises an exception on invalid base64 string.

**Comment by lebedev-yury** [comment]
```
> Base64.strict_decode64('data:image/jpeg;base64,/9j/4AAQSk ZJRg
ABA QEASABKdhH//2Q==')
ArgumentError: invalid base64
```

**Comment by lebedev-yury** [comment]
@sjdrabbani I understand this, but unfortunately whitespace is not the only thing that might be wrong in the base64 string, and we won't raise exceptions for every single case.

We can also remove 2 validations on lines 11 and 12 of `base64_string_io.rb` by using `string_decode` btw

**Comment by lebedev-yury** [comment]
@sjdrabbani thank you, it looks much better now. Can you please also delete the lines 11-12 in `base64_string_io.rb`, and change the spec `base64_string_io_spec.rb` on line 48 to expect a usual `ArgumentError`?

**Comment by sjdrabbani** [comment]
@lebedev-yury done as you have recommended. It looks cleaner now.

**Comment by lebedev-yury** [comment]
👍 great, thank you!

I'm merging this, and will release a new tiny version today

**Pull request merged**
